version: "3"

include:
    - proxy.yaml

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.python
        container_name: web
        ports:
            - "5000:5000"
        env_file:
            - ./.env-python
        networks:
            backend:
                ipv4_address: 172.20.0.5
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure

    db:
        container_name: db
        image: mysql:8
        ports:
            - "3306:3306"
        env_file:
            - ./.env
        networks:
            backend:
                ipv4_address: 172.20.0.10
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
            timeout: 20s
            retries: 10
        restart: on-failure

networks:
      backend:
            driver: bridge
            ipam:
              config:
                  - subnet: 172.20.0.0/24
